language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
before_deploy:
  # Set up git user name and tag this commit
  - git tag -d LATEST
  - git config --local user.name "frednordell"
  - git config --local user.email "fred@nordells.nu"
  - git tag LATEST
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: zlpRyPbjqVGV8hPSSUJ1lzyMR9bGKF8yVHK7agiG7+cx7sfMZpi71KvwQqJeCUdDLYZmmzPOCKX3hpe5mP/OZc79GPPb3rZzpUTtpujoOlQrEITxVK8SbOczUEHn+H7HSjykSeZ7G2XgqCUK5YTgvHni3q30Li1zgmFeaj5Jio8mcitpTTNrnGblpi8/wt8eT7ZaUFmzdouzNMXnaqrd+/zk6Zcy5pnkKmdTLji6ApWsE6/KTl2BPiW2Dxb/xAr3aZJzN01qmmRZXNDw5gfQmsJlUyQ3R5QCBg53oYYiCae7JgHIpf2ydIvUksNkYUfEILeqf6b5UKgfjFoank6I/2x2Haokm30QhUfQ/KwN+ZpePvbKuEakkVHnFY5dJFmryNLtiaHUIVFXuFoQyY4WbddW4EZ99nzTqOXp8bnvg0qu+29YrPrl5Rvpu65qOi1qLM2fKirRknmOHZKRKDP1lfme90PF3E381DrU9S1jn7A1pDHw1nKN/fFqDvaSNLEeVljWC9Y6QqhHjUMaMrfTQUFsHOFhhNUGcG+Y2gsXVicRR3aANGp4NJzUWGh/Kxk1gUhYrtBbfazNErcqskQunCejamHLAgiHw5f0gnZfEHUvAzK8S13RdPcTld0T2Q2bb65CV4wibAEMDxrgJsWcbpwoJO08O9GeVltp1l8EbdA=
  file: build/*
  on:
    repo: frednordell/nolla.nu-before
